excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://vamosfalardejs.github.io
title: Vamos Falar de JS?
tagline: console.log("Olá Mundo!");
description: My awesome new site
paginate: 4